---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

常用分析物件的指令
typeof,class,`str`

# 打了 str 才知道裡面的  $ results: 這段

# 下面這三行在解釋 $ results
# ..- attr(*, "dimnames")=List of 2
# .. ..$ : NULL
# .. ..$ : chr [1:4] "Package" "LibPath" "Item" "Title"
```{r}
dn <- data()
str(dn) 
```

```{r}
attributes(dn)
```


# 下面 Package 解釋
```{r}
dn$results
```


# NULL表示甚麼都沒有，可以不用管
```{r}
dimnames(dn$results)
# dsname <- ??????
```

# 矩陣 oo <- matrix(c(1,2,3,4,5,6),2,3)


```{r}
head(dn$results)
```

```{r}
dimnames(dn$results)
class(dn$results)
dsname <- dn$results[,"Item"]  ## daname <- dn$results[,3]
head(dsname)
```

dsname[dsname=="BOD]

length(dsname[dsname=="BOD"])

length(dsname[dsname=="xxx"])


## not in function(prior function)

```{r}
uname <- "BOD"
length(dsname[dsname==uname])
```

```{r}
isDsExists <- function(given){
  dn <- data()
  dsname <- dn$results[,"Item"] # dsname <- dn$results[,3]
  rst <- length(dsname[dsname==given])
  if(rst!=0){
    return(T)
  }
  else{
    return(F)
  }
}
isDsExists("iris")
```

```{r}
isDsExists <- function(given){
  dn <- data()
  dsname <- dn$results[,"Item"] # dsname <- dn$results[,3]
  rst <- length(dsname[dsname==given])
  if(rst!=0){
    return(T)
  }
  else{
    return(F)
  }
}
isDsExists("iris")


```

## note

3.要列出5個統計量

要知道資料集裡面有什麼欄位:name(cars)
要知道錢10筆資料:head(cars),tail(cars)