---
title: "home"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#基本

```{r}
x<-3
x1<-c(1,2,3)
x2<-c(TRUE,FALSE,TRUE)
```
```{r}
x
```
```{r}
x1
```
```{r}
x2
```

##統計量

c()是一個函數，用來形成一個向量函數。

- length()  :長度
- mean()  :平均數
- median()  :中位數
- var()  :變異數
- quantile()  
- sd() :標準差 
- fivenum()  


```{r}
x<-c(2,3,4,6,7,4,3,2,9)
length(x)
mean(x)
median(x)
var(x)
quantile(x)
sd(x)
fivenum(x)
range(x)
min(x)
max(x)
```



```{r}
x<-runif(4000)
length(x)
mean(x)
median(x)
var(x)
quantile(x)
sd(x)
fivenum(x)
range(x)
min(x)
max(x)
```

```{r}
x<-c(1,2,3)
y<-c(1,2)
```

```{r}
x<-c(1,2,3,4,5,6,7)
y<-c(1,2)
```

```{r}
x<- seq(0, 1, by = 0.2)
x
```

```{r}
x <- seq(0, 1, by = 0.3)
x[1]  
x[2]  
x[3]  
x[4]  
x[5]  
x[0]  
```

```{r}
x <- seq(0, 1, by = 0.3)

x<0.5

```

```{r}
x1<-c(T,T,F,T)
x2<-c(F,F,F,T)
x1 | x2
x1 & x2

```

```{r}
x <- c(1,2,3,4,5,6,7)
x[3]

idx <- c(1,3,5,7)
x[idx]

x[c(1,3,5,7)]
length(x[-7])
```
